spring:
  data:
    mongodb:
      database: ${MONGODB_COLLECTION:brs}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGDB_PORT:27017}

#logging:
#  level: debug

management:
  endpoints:
    web:
      exposure:
        include:*
server:
  error:
    whitelabel:
      enabled: false
